name: Doxygen
on:
  push:
    branches:
      - main
jobs:
  gendocs:
    runs-on: ubuntu-latest
    steps:
      # Checkout ESPixelStick
      - uses: actions/checkout@v2

      - name: Build doxygen pages
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: '.doxygen'
          doxyfile-path: 'Doxyfile'

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .doxygen/doc/html
          target-folder: /doxygen
          single-commit: true
